version: 2
jobs:
  build:
    docker:
      - image: billryan/gitbook
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /gitbook
    steps:
      - checkout
      - run:
          name: plugin install
          command: gitbook install
      - run:
          name: build
          command: gitbook build
      - persist_to_workspace:
          root: /gitbook
          paths:
            - .
  deploy:
    docker:
      - image: node:latest
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
    working_directory: /gitbook
    steps:
      - attach_workspace:
          at: /gitbook
      - run:
          name: test
          command: ls -l
      - run:
          name: install
          command: npm install
      - run:
          name: configset2
          command: mkdir ~/.ssh/
      - run:
          name: configset2
          command: touch ~/.ssh/known_hosts ; chmod 644 ~/.ssh/known_hosts
      - run:
          name: configset2
		  command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: configset
          command: git config --global user.name  "CircleCI"
      - run:
          name: configset2
          command: git config --global user.email "circleci@gh-pages.com"
      - run:
          name: deploy
          command: npm run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 
